const ALLOWED_DRILLDOWN_CLASS_NAMES =  ["dashboardSingleStateWidget", "dashboardWidget"];
const GITHUB_REPO = "gain-growth";
const GITHUB_OWNER = "Hena-123";
const GITHUB_REF_BRANCH = "GG-9-test";
const GITHUB_TOKEN = "<GITHUB_TOKEN>";

export {ALLOWED_DRILLDOWN_CLASS_NAMES, GITHUB_OWNER, GITHUB_REPO, GITHUB_REF_BRANCH, GITHUB_TOKEN}