export const UPDATE_FDS = "UPDATE_FDS";
export const GET_FDS = "GET_FDS";

export const UPDATE_INVESTMENTS = "UPDATE_INVESTMENTS";
export const GET_INVESTMENTS = "GET_INVESTMENTS";

export const CLEANUP_ALL = "CLEANUP_ALL";

export const GET_DATA_AVAILABILITY = "GET_DATA_AVAILABILITY";
export const SET_DATA_AVAILABILITY = "SET_DATA_AVAILABILITY";

export const GET_INVALIDSHEET = "GET_INVALIDSHEET";
export const SET_INVALIDSHEET = "SET_INVALIDSHEET";